### ISSUE TITLE
Turvis Rulesets as YAML DSLs

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Turvis#19]
AS A SecOps Engineer
I WANT TO create Turvis rulesets
SO THAT I could use Turvis the way it's meant to be used

### Acceptance Criteria

- [ ] Rulesets in `YAML`
- [ ] Rulesets can call out other `template` rulesets

### Examples

As an example, Ruuter sends the whole request to Turvis, which then runs generic tests against that request

#### FYI - Turvis sees the whole request sent to Ruuter by the End Client

```js
curl 'https://ruuter.demo.buerokratt.ee/post-message' \
  -H 'authority: ruuter.demo.buerokratt.ee' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'cookie: chatJwt=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIiLCJjaGF0SWQiOiJlN2E5ZTMwNS1lOWZkLTQwOTAtOWE1Ny0wYTE2NmUwNDBmYjMiLCJpc3MiOiJkZW1vLmJ1ZXJva3JhdHQuZWUiLCJmb3J3YXJkVG8iOiIiLCJleHAiOjE2ODQ0MTI2MDEsImlhdCI6MTY4NDQwNTQwMSwianRpIjoiMDc1NDY0OWItYTQwNy00NDc4LTg1Y2EtNDY3MmE4YTVmOTdhIn0.cBW7Gh4KLeMtIv11pRHJypImxx54lPqF-Yks9RMmAYJd-4k_9JicKFHCuA7DczqXAM5pO7Yr-ajBtB_q695vy7QrNaqBNx5DnLF98GtVziwoIlE8czfXLb-Af4wtnh5dIHxbB3ClxHyPMN69-WJLcTgcJDwICeRUpQipTQ87B9g9o9mKIqpDow-CW4FE3UbM8W3IuirteD4uqx1DSNLhB-lT4GxSmdX28kGwmHYL6ERZj3NsB_9p2wMQ9ffSjoi-ijixS-j7PpL2aNd0LUUIrFNwP_IuomghhVbUq-XYy5A5pJ6xCgGXYej8XvLa7zkNV7a0A0znLL_g4El9N6mLhA' \
  -H 'origin: https://demo.buerokratt.ee' \
  -H 'pragma: no-cache' \
  -H 'referer: https://demo.buerokratt.ee/' \
  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
  --data-raw '{"chatId":"e7a9e305-e9fd-4090-9a57-0a166e040fb3","content":"Hello! What is your name?","authorTimestamp":"2023-05-18T10:23:54.424Z","authorRole":"end-user"}' \
  --compressed
```

#### Step 1  - validate that incoming request's headers contain `chatJwt` and `origin` as keys

`general_ruleset.yml`

```yaml
validate_headers:
  headers:
    existsAndIsUnique: ["cookie.chatJwt", "origin"]
```

#### Step 2 - validate that End Client's message's structure is the exact match to what we expect it to be

`general_ruleset.yml`, in addition to previous step

```yaml
validate_content:
  body:
    keyExactMatch: ["chatId", "content", "authorTimestamp", "authorRole"]
```

_The above applies to `--data-raw` section of original request input_

#### Step 3 - apply validation against regular expressions of specific parts of request

_In the example below, `pattern` indicates executing regex validations, `isUuid` and `timestampValid` are `TypeScript` files of regex validations and `chatId` and `timestamp` are request body contents_

```yaml
pattern_validation_on_body:
  body:
    pattern:
      isUuid: "chatId"
      timestampValid: "timestamp"
```
